config/routes.rb
Rails.application.routes.draw do
  get 'ingredients/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#public'
  get '/public_recipes', to: 'recipes#public'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  scope :recipes do
    get '/:id/publish', to: 'recipes#publish', as: :publish_recipe
  end

  scope :recipe_foods do
    delete '/:id/delete', to: 'recipe_foods#destroy', as: :delete_recipe_food
  end

  resources :recipes, shallow: true, except: [:edit, :update] do
    member do
      post 'publish'
    end
  end
  resources :foods, only: [:index, :destroy, :new, :create]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  def public?
    is_public
  end

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
  validates :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[is_public show]
  skip_authorize_resource only: :is_public

  def index
    @recipes = current_user.recipes.includes(:foods)
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    authorize! :read, @recipe
    @ingredient = RecipeFood.find_by(id: params[:id], recipe: @recipe)
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @recipe = Recipe.new
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    @recipe.recipe_foods.destroy_all

    @recipe.destroy
    redirect_to recipes_path
  end

  def public
    @totals = {}

    @public_recipes = Recipe.where(is_public: true).includes(:foods, :user).order('created_at DESC')
    @public_recipes.each do |pub|
      total = 0
      RecipeFood.where(recipe_id: pub.id).each do |rec_food|
        total += rec_food.quantity * rec_food.food.price
      end
      @totals[pub.id] = total.round(2)
    end
  end

  def publish
    @recipe = Recipe.find(params[:id])
    @recipe.is_public = !@recipe.is_public

    redirect_to @recipe if @recipe.save
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :is_public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<section id='new-recipe' class="container mx-auto px-4 mt-5">
  <%= form_with model: recipe, class: "max-w-3xl w-3/4 p-4 bg-light rounded shadow" do |form| %>
    <% if recipe.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="text-danger"><%= pluralize(recipe.errors.count, 'error') %> prohibited this object from being saved:</h4>
        <ul>
          <% recipe.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label text-gray-700" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :preparation_time, class: "form-label text-gray-700" %>
      <%= form.text_field :preparation_time, class: "form-control", placeholder: "hours" %>
    </div>
    <div class="mb-3">
      <%= form.label :cooking_time, class: "form-label text-gray-700" %>
      <%= form.text_field :cooking_time, class: "form-control", placeholder: "hours" %>
    </div>
    <div class="mb-3">
      <%= form.label :description, class: "form-label text-gray-700" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :is_public, class: "form-label text-gray-700" %><br>
      <div class="form-check form-check-inline">
        <%= form.label :is_public_true, "Yes", class: "form-check-label mr-2", for: "recipe_public_true" %>
        <%= form.radio_button :is_public, true, checked: true, class: "form-check-input", id: "recipe_public_true" %>
      </div>
      <div class="form-check form-check-inline">
        <%= form.label :is_public_false, "No", class: "form-check-label mr-2", for: "recipe_public_false" %>
        <%= form.radio_button :is_public, false, class: "form-check-input", id: "recipe_public_false" %>
      </div>
    </div>
    <div>
      <%= form.submit "Add recipe", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</section>

app/views/recipes/index.html.erb
<section id='recipes' class="flex flex-col justify-center bg-gray-100">
  <div class="flex flex-col items-center">
    <% @recipes.each do |recipe| %>
      <div class="max-w-4xl w-11/12 m-4 p-6 bg-white border border-gray-200 rounded-lg shadow">
        <div class="space-y-4 dflex spacebetween">
          <div class="box1">
            <%= link_to recipe_path(recipe) do %>
              <p class="mb-3 text-gray-700"><%= recipe.name %></p>
            <% end %>
            <%= button_to 'Remove', recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
          </div>
          <p class="mb-3 text-gray-700 box2"><%= recipe.description %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center my-8">
    <%= link_to 'Add Recipe', new_recipe_path, class: "btn btn-success"  %>
  </div>
</section>

app/views/recipes/new.html.erb
<section id='mb-2 dflex flexcol'>
  <%= render 'form', recipe: @recipe %>
</section>

app/views/recipes/public.html.erb
<div class='text-center'>
  <h1 class="text-3xl font-bold my-4">Public Recipes</h1>
</div>
<% if @public_recipes.empty? %>
  <div class='text-center'>
    <h1 class="text-3xl font-bold my-8">Hello! We don't have any recipes yet!</h1>
    <p class='mb-5'>Please be the first to create one!</p>
    <% if current_user %>
      <%= link_to 'Create a recipe', new_recipe_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <% end %>
  </div>
<% else %>
  <div class="flex flex-col items-center">
    <% @public_recipes.each do |recipe| %>
      <div class="max-w-4xl w-11/12 m-4 p-6 bg-white border border-gray-200 rounded-lg shadow">
        <div class="space-y-4 dflex spacebetween">
          <div class="box1">
            <%= link_to recipe_path(recipe) do %>
              <div class="title1"><%= recipe.name %></div>
            <% end %>
            By: <%= recipe.user.name %>
          </div>
          <div class="box3">
            <div>
              <span>Total food items:</span>
              <span><%= recipe.foods.length %></span>
            </div>
            <div>
              <span>Total price:</span>
              <span class="text-green-500">$<%= @totals[recipe.id] %></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<section id='recipe' class="container mx-auto px-4">
  <header class='text-center'>
    <h1 class="text-3xl font-bold my-4">Recipe <%= @recipe.name %></h1>
  </header>
  <main class='recipe'>
    <div class="card mb-4">
      <div class="card-body">
        <p class="card-text">Preparation time: <%= @recipe.preparation_time %> hours</p>
        <p class="card-text">Cooking time: <%= @recipe.cooking_time %> hours</p>
        <p class="card-text"><%= @recipe.description %></p>
      </div>
    </div>
    <div class="text-center mb-4">
      <% if can?(:manage, @recipe) %>
        <% if @recipe.is_public %>
          <%= link_to "Unpublish", publish_recipe_path(@recipe), method: :post, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Publish", publish_recipe_path(@recipe), method: :post, class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </main>
  <div class="d-flex justify-content-between mb-4">
    <%= link_to 'Generate shopping list',
      general_shopping_list_path,
      id: 'generate-shopping-list-2',
      data: { recipe_id: @recipe.id },
      class: 'btn btn-primary',
      if: can?(:manage, @recipe)
    %>
    <% if can?(:manage, @recipe) %>
      <%= link_to 'Add ingredient', new_recipe_food_path(recipe_id: @recipe.id), class: "btn btn-secondary" %>
    <% end %>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <% if can?(:manage, @recipe) %>
            <th scope="col">Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |ingredient| %>
          <tr>
            <td><%= ingredient.food.name %></td>
            <td><%= ingredient.quantity %></td>
            <td><%= ingredient.quantity * ingredient.food.price %></td>
            <% if can?(:manage, @recipe) %>
              <td class="dflex">
                <%= link_to 'Edit', edit_recipe_food_path(ingredient), class: 'btn btn-primary mx-8' %>
                <%= form_with url: delete_recipe_food_path(ingredient), method: :delete do |form| %>
                  <%= form.submit 'Remove', data: { confirm: 'Are you sure you want to delete this food?' }, class: 'btn btn-danger' %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>
<script>
  document.getElementById('generate-shopping-list-2').addEventListener('click', function(event) {
    event.preventDefault();
    const recipeId = this.getAttribute('data-recipe-id');
    localStorage.setItem('selectedRecipeId', recipeId);
    window.location.href = this.href + '?selected_recipe_id=' + recipeId;
  });
</script>