config/routes.rb
Rails.application.routes.draw do
  get 'ingredients/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#public'
  get '/public_recipes', to: 'recipes#public'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  scope :recipes do
    get '/:id/publish', to: 'recipes#publish', as: :publish_recipe
  end

  scope :recipe_foods do
    delete '/:id/delete', to: 'recipe_foods#destroy', as: :delete_recipe_food
  end

  resources :recipes, shallow: true, except: [:edit, :update] do
    member do
      post 'publish'
    end
  end
  resources :foods, only: [:index, :destroy, :new, :create]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def generalinfo
    "#{name}  --  $#{price} x #{measurement_unit}"
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def edit
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    existing_food = current_user.foods.find_by(name: food_params[:name].strip.capitalize)
    if existing_food
      existing_food.quantity += food_params[:quantity].to_f
      existing_food.price = food_params[:price].to_f
      if existing_food.save
        redirect_to foods_path, notice: 'Quantity added to existing food.'
      else
        render :new
      end
    else
      # If no existing food with the same name is found, create a new one
      @food = Food.new(food_params)
      @food.name = @food.name.strip.capitalize
      @food.measurement_unit = @food.measurement_unit.strip.capitalize
      @food.user = current_user
      if @food.save
        redirect_to foods_path, notice: 'Food was successfully created.'
      else
        render :new
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])

    # Find and delete associated recipe_foods records
    RecipeFood.where(food_id: @food.id).destroy_all

    @food.destroy
    redirect_back_or_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/views/foods/_form.html.erb
<div class='text-center'>
  <h1 class="text-3xl font-bold my-8">Add a new Food</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 mx-auto">
      <%= form_with(model: @food, url: foods_path, local: true, class: "form-horizontal") do |form| %>
        <div class="form-group">
          <%= form.label :name, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= form.text_field :name, class: "form-control", placeholder: "Enter Food Name" %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :measurement_unit, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= form.text_field :measurement_unit, class: "form-control", placeholder: "Enter Measurement Unit" %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :price, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= form.number_field :price, step: '0.01', class: "form-control", placeholder: "Enter Price" %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :quantity, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= form.number_field :quantity, step: '0.01', class: "form-control", placeholder: "Enter Quantity" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= form.submit 'Create Food', class: "btn btn-primary" %>
            <%= link_to 'Back', foods_path, class: 'btn btn-secondary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/edit.html.erb
<section id='edit-foods'>
  <%= render 'form', foods: @foods %>
</section>

app/views/foods/index.html.erb
<section id='food-list' class="container my-4">
  <% if @foods.empty? %>
    <div class='text-center'>
      <h1 class="text-3xl font-bold my-8">Hello! We don't have any food!</h1>
    </div>
    <div class="text-center d-flex justify-content-center my-4">
      <%= link_to 'Add Food', new_food_path, class: 'btn btn-primary ml-5 float-right mb-5' %>
    </div>
  <% else %>
    <div class="text-center d-flex justify-content-end my-4">
      <%= link_to 'Add Food', new_food_path, class: 'btn btn-primary ml-5 float-right mb-5' %>
    </div>
  <%# end %>

    <table class="table table-bordered">
      <thead>
        <tr class="bg-primary text-white">
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Measurement Unit</th>
          <th scope="col">Unit Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.measurement_unit %></td>
            <td>$<%= food.price %></td>
            <td>
              <%= form_with url: food_path(food), method: :delete do |form| %>
                <%= form.submit 'Delete Food', class: 'btn btn-danger' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>

app/views/foods/new.html.erb
<section id='mb-2 dflex flexcol'>
  <%= render 'form', foods: @foods %>
</section>