config/routes.rb
Rails.application.routes.draw do
  get 'ingredients/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#public'
  get '/public_recipes', to: 'recipes#public'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  scope :recipes do
    get '/:id/publish', to: 'recipes#publish', as: :publish_recipe
  end

  scope :recipe_foods do
    delete '/:id/delete', to: 'recipe_foods#destroy', as: :delete_recipe_food
  end

  resources :recipes, shallow: true, except: [:edit, :update] do
    member do
      post 'publish'
    end
  end
  resources :foods, only: [:index, :destroy, :new, :create]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :check_recipe_ownership, only: [:new]

  def new
    @recipe_food = RecipeFood.new
    @recipe_food.recipe_id = params[:recipe_id]
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    recipe = Recipe.find(@recipe_food.recipe_id)

    return unless can?(:manage, recipe)

    if @recipe_food.save
      redirect_to @recipe_food.recipe, notice: 'Food added to recipe successfully.'
    else
      puts @recipe_food.errors.full_messages
      redirect_to new_recipe_food_path
    end
  end

  def destroy
    return unless can?(:manage, @recipe_food.recipe)

    @recipe_food = RecipeFood.find(params[:id])
    recipe_id = @recipe_food.recipe_id

    if @recipe_food.destroy
      redirect_to recipe_path(recipe_id), notice: 'Food deleted successfully.'
    else
      puts @recipe_food.errors.full_messages
      redirect_to recipe_path(recipe_id), alert: 'Failed to delete food.'
    end
  end

  def edit
    unless can?(:manage, @recipe_food.recipe)
      redirect_to root_path, alert: 'You do not have permission to edit this food in the recipe.'
      return
    end

    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe), notice: 'Quantity updated successfully.'
    else
      render :edit
    end
  end

  private

  def check_recipe_ownership
    recipe = Recipe.find(params[:recipe_id])
    return if can?(:manage, recipe)

    redirect_to root_path, alert: 'You do not have permission to add food to this recipe.'
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity, :recipe_id)
  end
end

app/views/recipe_foods/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="text-3xl font-bold mb-4 text-center">Edit ingredient quantity</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @recipe_food, url: recipe_food_path(@recipe_food), method: :patch, class: 'edit-recipe-food-form') do |form| %>
            <div class="mb-3 dflex spacebetween">
              <%= @recipe_food.food.name %>:  <%= form.label :quantity, class: 'form-label' %> <%= form.number_field :quantity, class: 'quantity-placeholder' %><%= @recipe_food.food.measurement_unit %>
            </div>
            <div class="text-center">
              <%= form.submit 'Update Quantity', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container mt-5">
  <h2 class="mb-4">Add Food to Recipe</h2>

  <%= form_for @recipe_food, class: 'mb-4' do |f| %>
    <div class="mb-3">
      <%= f.label :food_id, 'Food', class: 'form-label' %>
      <%= f.collection_select :food_id, current_user.foods, :id, :generalinfo, { prompt: 'Select a Food' }, class: 'form-select' %>
    </div>

    <div class="mb-3">
      <%= f.label :quantity, class: 'form-label' %>
      <%= f.number_field :quantity, step: '0.01', class: 'form-control' %>
    </div>

    <%= f.hidden_field :recipe_id %>

    <div class="d-flex  mb-4">      
      <%= f.submit 'Add Food', class: 'btn btn-primary me-4' %>
      <%= link_to 'Back', :back, class: 'btn btn-success ms-4' %>
    </div>
  <% end %>

</div>