config/routes.rb
Rails.application.routes.draw do
  get 'ingredients/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'recipes#public'
  get '/public_recipes', to: 'recipes#public'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  scope :recipes do
    get '/:id/publish', to: 'recipes#publish', as: :publish_recipe
  end

  scope :recipe_foods do
    delete '/:id/delete', to: 'recipe_foods#destroy', as: :delete_recipe_food
  end

  resources :recipes, shallow: true, except: [:edit, :update] do
    member do
      post 'publish'
    end
  end
  resources :foods, only: [:index, :destroy, :new, :create]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class='footer text-center'>here's the footer</footer>

app/views/layouts/_nav.html.erb
<nav class="bg-gray-800">
  <% if current_user %>
    <div class='dflex spacebetween'>
      <div>
        <%= link_to 'Foods', foods_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium' %>
        <%= link_to 'Recipes', recipes_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium' %>
        <%= link_to 'Public Recipes', public_recipes_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium' %>
        <%= link_to 'Generate shopping list',
          general_shopping_list_path,
          id: 'generate-shopping-list',
          class: 'bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded',
          if: can?(:manage, @recipe)
        %>
      </div>
      <div>
        <%= link_to "Sign Out", custom_destroy_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
      </div>
    </div>
  <% else %>
    <%= link_to "Log in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
  <% end %>
</nav>
<script>
  document.getElementById('generate-shopping-list').addEventListener('click', function(event) {
    event.preventDefault();
    const selectedRecipeId = localStorage.getItem('selectedRecipeId');
    if (selectedRecipeId != null) this.href += '?selected_recipe_id=' + selectedRecipeId;
    window.location.href = this.href;
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div class="alert-notice">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>